//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.20 at 08:33:03 PM EST 
//


package com.tom.jaxbxml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link Containers }
     * 
     */
    public Containers createContainers() {
        return new Containers();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link ShipmentLines }
     * 
     */
    public ShipmentLines createShipmentLines() {
        return new ShipmentLines();
    }

    /**
     * Create an instance of {@link Extn }
     * 
     */
    public Extn createExtn() {
        return new Extn();
    }

    /**
     * Create an instance of {@link ShipmentLine }
     * 
     */
    public ShipmentLine createShipmentLine() {
        return new ShipmentLine();
    }

    /**
     * Create an instance of {@link ContainerDetails }
     * 
     */
    public ContainerDetails createContainerDetails() {
        return new ContainerDetails();
    }

    /**
     * Create an instance of {@link ContainerDetail }
     * 
     */
    public ContainerDetail createContainerDetail() {
        return new ContainerDetail();
    }

}
