//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.20 at 08:33:03 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Shipment1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tom.jaxbxml;
